### ISSUE TITLE
Performance optimization for level view

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#10]
> ### Redmine metadata
> 
> | Attribute | Value |
> | --- | --- |
> | done_ratio | 0 |
> | status | New |
> | start_date | 2015/11/11 |
> | created_on | 2015/11/11 12:57:29 +0100 |
> | author | florian |
> | priority | Normal |
> | updated_on | 2016/09/18 19:57:49 +0200 |
> | tracker | Bug |
> | asigned_to | None |

---

for example http://localhost:5000/facilities/buildings/Wu5/levels/13/rooms/
## 

_This issue has been automatically imported from redmine on 2016-09-28 19:07:43.927398_

**Comment by lukasjuhrich** [comment]
> ### Redmine metadata
> Attribute | Value
> ------------ | --------
> created_on | 2015/11/11 13:00:45 +0100
> user | florian


---
Maybe the cause of this is the flask development web server.

--
_This comment has been automatically imported from redmine on 2016-09-28 19:07:46.520232_

**Comment by toothstone** [comment]
This **must** be resolved before deployment. The most used support view (rooms on a level) takes >5 seconds to load, which is unbearable.

**Comment by lukasjuhrich** [comment]
@toothstone I changed the project to „bare minimum“.

However, I cannot reproduce the bug you are referring to.

On a local installation, calling `http://localhost:5000/facilities/buildings/Wu3/levels/2/rooms/json` takes 1.576s – still a lot, but not 5 seconds. 
Remember, it has to query the whole user database, which currently spans 10977 entries (at least from my dump).

I will try to rebuild (and, in the process automate the building perhaps a bit) the dev-container.

**Comment by mueslo** [comment]
This is a valid issue. The problem with level view for example is that for each user a seperate ORM query is issued, which is then individually styled.

**Comment by lukasjuhrich** [comment]
@mueslo I don't really see how this can be easily resolved.
One of the main problems is that the status of the user must be known (using `lib.user.status`), which consists of multiple cases each being realized by various standalone queries. This is way outside the model, but also belongs there, logically speaking.

I get responses of <100ms when commenting out `is_member(user)` and `user_button(user)`, leaving the first in in results in ~800ms and leaving the second one in results in 1.7s.

Except for super fancy shit (like adapting bootstrap-tables to allow for a two-stage loading which first displays you only the users name and adds artifacts lazily) I don't really see a fix here.

**Comment by mueslo** [comment]
A single page fetch shouldn't result in 500+ database queries, there's something definitely wrong ;)
```

--------------------------------------------------------------------------------
PATH: '/facilities/buildings/Wu7/levels/2/rooms/json'
         616715 function calls (586400 primitive calls) in 2.360 seconds

   Ordered by: internal time, call count
   List reduced from 1161 to 30 due to restriction <30>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      588    1.059    0.002    1.064    0.002 {method 'execute' of 'psycopg2.extensions.cursor' objects}
   [...]
```

**Comment by janLo** [comment]
@lukasjuhrich  Have a look at http://docs.sqlalchemy.org/en/latest/orm/loading_relationships.html#using-loader-strategies-lazy-loading-eager-loading

**Comment by lukasjuhrich** [comment]
@janLo Thanks, I already looked over it. These options do not help in this case however, since after the rooms and the users have been loaded, the main information is determined by library functions which do not use any declarative ORM logic and thus do not build queries SQLAlchemy understands. This means while the user can be loaded eagerly, there is no option for SQLAlchemy to know how to efficiently query the other information, which is defined imperatively. I hope that makes sense.

AFAIK @mueslo is trying to build a query to bulk-fetch status information like in [pycroft.lib.user.status](https://github.com/agdsn/pycroft/blob/develop/pycroft/lib/user.py#L502) for user objects.

**Comment by mueslo** [comment]
@lukasjuhrich this is irrelevant IMO, it is still possible to reduce the queries by eagerly loading some relationships. However, the crux of the problem is that, as far as I can tell, hybrid attributes cannot be eagerly loaded.

**Comment by lukasjuhrich** [comment]
I do agree that further optimization can be done, but as I don't really think it's a _critical_ time difference, would there be any objections to removing this card from the “Bare Minimum” Project (e.g. @toothstone)?

**Comment by toothstone** [comment]
The currently running test deployment performs okay for me, so no objection from me :)

**Comment by lukasjuhrich** [comment]
Just a side note, one could perhaps utilize the `current_property` view (See #161). However, the level overview needs to know memberships (like in `config.member_group`) and not only properties.

A possibility to circumvent this would be to introduce a property for this like `is_member` and `is_external`. On the first sight this might look like an unnecessary relationship and a cluttering of pycroft with properties, but the pycroft model is designed to be really efficient in asking for properties. Also, joining the `Property` table in which the grants are stored should be negligible as it has only ~50 entries and is not apt to grow significantly.

**Comment by sebschrader** [comment]
On the contrary. Using groups for that is the anti-feature the overview uses, it should have been a property in the first place.

Being a member of the AG DSN is definitely a property in the strictest sense.

**Comment by lukasjuhrich** [comment]
I'm realizing that this would and the discussion concerning whether to add an `external` group to the config or not.
