### ISSUE TITLE
Heuristic Schema check

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#102]
It would be convenient to fail starting pycroft when the given database does not have the correct schema yet.

The current use case would be that the importer has not been run yet, so a heuristic checking for the existance of all the tables would be sufficient. Check out e.g. [this SO thread](https://stackoverflow.com/questions/30428639/check-database-schema-matches-sqlalchemy-models-on-application-startup#30653553)

**Comment by sebschrader** [comment]
What about versioning the schema and having a schema_version table with a single row containing the version?

**Comment by lukasjuhrich** [comment]
That sounds better and is not too difficult. Closing, since there's no benefit of putting the work into such a hack right now.
