### ISSUE TITLE
Device Search

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#104]
In the Hausübersicht one could search for users using attributes like the IP or MAC-Address. This should be implemented as a way to search for hosts.

Wildcard matching should not be necessary, the requirements are just a simple way to e.g. paste an IP address and find the corresponding host / user (a host overview page does not exist).

**Comment by mmarx** [comment]
It's not _so_ simple. MAC addresses, e.g., can come in a variety of different formats, and you want to be able to paste any of those into the search box and get the matching results, even if they have a different format (presumably, there is some kind of normalisation involved?).

For IP addresses, being able to specify a subnet (say, 10.11.12/23) and getting back all matching IPs would be nice to have.

**Comment by toothstone** [comment]
> Wildcard matching should not be necessary

I have to object, at least for MAC addresses I need that quite often, to spot off-by-one errors and similar.
