### ISSUE TITLE
Show non-AGDSN members in rooms overview

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#105]
Because only people having the `member` property are shown, users from partners such as the StudentenWerk are not shown in the level overview.

A good filter has to be chosen that remains not showing people who moved out and thus do not have access anymore.

**Comment by lukasjuhrich** [comment]
I just realized this can be fixed by including members of `extern` in this list.

**Comment by lukasjuhrich** [comment]
The actual solution is to display **every** user living in that room. The actual problem here is that in the netusers system, there was no workflow for deleting users, so there's a _huge_ bunch of old accounts that should be deleted some time (i.e., soon after deploying pycroft). But these accounts are just noise when looking at a usual Wundtstrasse Facility.

So:

- Enforcing users to be members does not work for the Budapester Straße Site
- Not enforcing that does not work for the rest of the netusers-Administrated Dormitories

Instead of enforcing one of the options, implementing guesswork or hard-Coding the `extern` group into pycroft, I propose to make it **togglable** whether one wants to include everyone or just members.

**Comment by sebschrader** [comment]
We need to query different properties then such as ”network_access" or "mail". Usually you want to see all users that are eligible to receive services from us (and therefore have the aforementioned properties) and not their actual AG DSN membership state.

Ideally one could select the properties that are used to filter the users in the overview, but that would be a wishlist feature.
