### ISSUE TITLE
Use `python` base image for docker

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#107]
The current Dockerfile uses a full debian base image.
The python images have two advantages:

- They are low-noise, i.e. contain only the tools necessary for developing in python
- They provide version tags so fixing the python version is easier.

When addressing this issue, a general cleanup would be good, such as removing programs that are unnecessary for a production release, removing the legacy vagrant setup etc.

It might be worth it to split up the docker images into a minimal, production base image and two forks providing packages necessary for testing and useful for development (debugging?).

**Comment by sebschrader** [comment]
TBH there are more important things to do. Switching to another base image doesn't provide us with anything

**Comment by lukasjuhrich** [comment]
Closing, as we already use `python` in the new docker setup.
