### ISSUE TITLE
Remove Bower Stack from pycroft

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#108]
We should utilize [multi-stage builds](https://docs.docker.com/engine/userguide/eng-image/multistage-build/) to remove the bower stack from the docker image which is completely unnecessary for running and just takes up space.

**Comment by sebschrader** [comment]
As a side note: The JavaScript world moves very fast and changes a lot. It is amazing how much “innovation” is possible in the realm of package management. There are at least three package manager for JavaScript right now, `bower`, `npm` and `yarn`. `Bower` is apparently [deprecated](https://bower.io/) and one should use [`yarn`](https://yarnpkg.com/) for frontend stuff as far as I understand it.

**Comment by lukasjuhrich** [comment]
I heard about that, thanks for noting it here.

**Comment by sebschrader** [comment]
I have created a new build pipeline for our frontend assets based on yarn and webpack. Due to being a major change, it requires documentation.

I'll see, if I can open a branch/PR this week.

**Comment by ibot3** [comment]
Bower is not used anymore.
