### ISSUE TITLE
Manage cache opt-in

### ISSUE THREAD

**Issue by toothstone** [agdsn/pycroft#113]
We should at least display if a user has opted-in for the cache, even better would be the possibility to toggle that as in the Hausübersicht.

**Comment by lightning1** [comment]
This needs a representation in the model, since the implementation in Hausübersicht is currently the authoritative backend for the usage of the cache.

**Comment by sebschrader** [comment]
I would advise against integrating the cache model into Pycroft. If we have learned anything from its development, it is that smaller, more focussed projects are much more likely to succeed. It would also be easier for new people to maintain and extend. The cache is something that doesn't benefit very much from integration into Pycroft.

If there is any reason to display cache usage in Pycroft or SIPA it should be done via an API.

**Comment by lightning1** [comment]
This sounds great but will produce significant more work, because:
- there is currently no other place for (user-)settings than Pycroft
- communication between SIPA and Pycroft is required anyway
- there is no API at all for the cache
- the DNS resolving needs permanent knowledge of the assigned IPs of a user

I think the cache project is more likely to die if we generate additional requirements in contrast to adding a simple boolean value to the user object in Pycroft.

The reason to show and maybe change the state is relevant for support tasks.

**Comment by sebschrader** [comment]
OK, if it's only the user setting we're talking about, I'm totally with you.

“Cache usage” could have meant much more (statistics etc.).

**Comment by lightning1** [comment]
Jep, this was misleading. The current setting located in the netusers.nutzer table is called "use_cache", which is a simple boolean value. I should've mentioned that.

The only statistics planned right now are global once and not user dependent. As far as i know, @MarauderXtreme is currently on it. They will be independent of any user management system.

**Comment by sebschrader** [comment]
Maybe the title of the issue should be changed accordingly.

Pycroft's property system is an obvious fit for this functionality, so that no model change should be necessary.

**Comment by toothstone** [comment]
Afaik this is what the flexible group system has been made for, but I was not able to create a new group in the current test deployment. It's probably best to just integrate this in the importer, anyway.

> “Cache usage” could have meant much more
Maybe read the whole issue the next time ;)

**Comment by toothstone** [comment]
This should also be added to the importer, which would also take care of creating the group.

**Comment by sebschrader** [comment]
A distinguished group should probably be added to the config model for this purpose, so that Pycroft knows which group typically grants the cache property.

**Comment by lukasjuhrich** [comment]
Thanks @toothstone for taking a look at this and for the following lively discussion. In fact, you pointed me to a bug I recently fixed (see 211158cfe12bb710eadc8b3a952ee128c03a075f, 6594058fdd68eb7f381c3cfe3c632519ab47f2e7).

The solution of using a property group seems fine, although I would focus on different issues right now than to integrate this property group into the model. This can be done in a later point in time as well, and the core functionality (granting the property) is in essence already available.

@sebschrader note that currently, the UI does not provide any workflow for creating new _properties_, except for manually adding an entry to the database.

**Comment by sebschrader** [comment]
You can't grant properties to users, only group memberships. How would you do that without having a special opt-in group that grants the opt-in property?

**Comment by lukasjuhrich** [comment]
Similar to [this comment](https://github.com/agdsn/pycroft/issues/98#issuecomment-342052739), I now understand that it's fairly simple to implement using a property. It would incorporate:

- [ ] Adding a field `cache_group` to the pycroft `Config` model
- [ ] Creating this group in the importer and add a membership for all the users who have the netusers flag, adn granting this group the property `use_cache`
- [ ] Add a simple Icon to the `user_show` overview indicating whether the user currently uses the cache (toggling the cache should be done by adding/terminating memberships IMHO)
- [ ] Incorporate in the Hades Views (see #101) the fact that a user has or has not the property `use_cache`.
- [ ] Tests, of course. ;-)

The model change and the UI indicator form a quite simple and isolated task. Perhaps this is a good follow-up issue for @marcelb98?

**Comment by toothstone** [comment]
Maybe @Paktosan wants to have a look.

**Comment by lukasjuhrich** [comment]
@Paktosan the cache-column in the netusers is of type `tinyint(1)` (the usual bool-datatype), non-nullable, default 0. Because nullability and the default value don't matter in this case as we don't want to create the schema, you only need to add it as a bool-column and be happy.

**Comment by toothstone** [comment]
I increased the priority on this since the cache is now a semi-official feature and thus must be included in the database and hades views.
