### ISSUE TITLE
Offer the current credit amount as Materialized View 

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#129]
Without further optimizations, the frequent operation of getting the current credit of a user[1] can be extremely inefficient.
In any case, we would need to aggregate the complete history of traffic events. Depending on the granularity and length by which we store data[2], we would need to aggregate a lot of entries.

A optimization would be to create a materialized view with a regularly executed update routine (say, every hour) which provides an intermediate balance that can be used for the calculations.

It would be essential to use a fitting name to distinguish the view from the `balance` relation, such as `cached_balance` or `recent_balance`.

However, it is unclear at the moment how great the inefficiency actually is, keeping in mind that calculating the current credit only incorporates summing all entries grouping by a `user_id`.

[1] …as initiated for every user with every refresh of Hades' materialized wiews
[2] The plan for the future would be to regularly scrub the (finely granular, say 5 minutes) raw data from the pmacct to a user-configured interval. Before that, we would have a `TrafficVolume` every five minutes for, say, two weeks.

**Comment by lukasjuhrich** [comment]
The disadvantage with using a materialized view is that we need to refresh it using triggers (`ON INSERT/UPDATE` on split, if I see things correctly, but only if the referenced account is used by a user), which is additional functionality that would need to be tested.

**Comment by sebschrader** [comment]
Depends on what it'll be used for. If the data doesn't need to be up to date all the time, a deferred refresh by some other mechanism may suffice.
