### ISSUE TITLE
Configurable Traffic Backlog

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#131]
Every user should be able to specify a limit and granularity of the traffic backlog.

Besides the actual new attributes in the user model, a data scrubbing routine has to be implemented. It should aggregate every `TrafficVolume` (which is a priori added in 5min intervals by the pmacct) in the given duration to one entry, located at the beginning of the interval.

The scrubbing should be executed in intervals like e.g. one hour.

**Comment by ibot3** [comment]
I don't think that we need this feature anymore.
What do you think @lukasjuhrich ?

**Comment by lukasjuhrich** [comment]
Agreed, closing.
