### ISSUE TITLE
Materialized Views for traffic balance over time

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#132]
The traffic balance should be pre-computed in various granularities for easier calculation of the logs.

A refresh has to be enforced at least in the scrubbing (#131) and cleanup (#130) routines.

**Comment by sebschrader** [comment]
What's different between this issue and #129 ?

**Comment by lukasjuhrich** [comment]
This issue addresses a historic evolution, while #129 is only concerned with the current amount. We should definitely use consistent terminology, as the titles are indeed misleadingly similar.
I'm renaming #129.

**Comment by sebschrader** [comment]
Thanks for clarifying.
