### ISSUE TITLE
Remove different interface types

### ISSUE THREAD

**Issue by sebschrader** [agdsn/pycroft#139]
Let's carefully think about the network model. I think we don't need `ServerInterface` and `SwitchInterface` anymore. If we can get rid of them, we can also combine `UserInterface` and `Interface`. This would simplify our model.

**Comment by lukasjuhrich** [comment]
I don't see how the SwitchInterface would be superfluous. We need to track which user is connected to which port. Granted, we could undo the Interface polymorphism, and drop the MAC, however, the name, the corresponding switch, and the relationship to the hosts must remain.

**Comment by sebschrader** [comment]
The polymorphism is what bothers me the most, because it introduces a lot of complexity.

I suggest we remove `ServerInterface`, it's totally unneeded at this point, keep the bits from `SwitchInterface` we still need, remove the rest and rename it to `SwitchPort` and pull up `UserInterface` into `Interface`.

**Comment by lukasjuhrich** [comment]
+10. This definitely sounds like a good deal of simplification. It has been quite a frequent encounter that i confused an `interface` relationship with a `user_interface` one, because you _never ever ever ever_ use the `server_interface` side of the polymorphism.

Although this might result in some broad refactoring, I think this change will be worth it considering the Views for hades etc. will be significantly simpler to construct.

**Comment by lukasjuhrich** [comment]
Isolating `SwitchInterface` is surprisingly simple, the only common information introduced by `Interface` was the MAC address, which is the only thing useless about a `SwitchInterface`.

**Comment by lukasjuhrich** [comment]
One important thing though: I did not only remove `ServerInterface`, but `ServerHost` in its entirety. No code depends on it and I don't see a use case in that special case either.

The only use I see in it is the `name` attribute which only comes into play when generating DNS information from pycroft. However, we completely moved away from that path a few months ago by removing such parts from the model, so I consider this to be obsolete.

**Comment by lukasjuhrich** [comment]
@sebschrader removing `SwitchInterface` results in the problem that we don't know the IP of the switch anymore, and

**Comment by sebschrader** [comment]
I see no problem there. The IP addresses in the user networks, that we use and need to reserve, are owned by our system user (like we do now in our current system).

The management, RADIUS etc. IP addresses are special anyway. They are typically private addresses in totally different subnets (subnets we don't need to model in Pycroft). They should be attributes of the `Switch`.

**Comment by sebschrader** [comment]
The `Host`, `UserHost` and `Switch` polymorphism can be removed as well. If we want to keep the common fields of `UserHost` and `Switch`, `Host` could become an abstract base class.

**Comment by lukasjuhrich** [comment]
An IP cannot be owned directly by a user! it must be bound to an interface in the current model, which (I suspect) was the reason Switch was made a `Host` – so it could have interfaces with IPs.

**Comment by sebschrader** [comment]
You are right, but fortunately this doesn't kill my plan and inspired me for an even better solution ;-) .

Remove `ServerHost`, pull user host up `UserHost` into `Host` and detach `Switch` from the inheritance hierarchy and introduce a 0..1–1-relationship between `Host` and `Switch`. From an object-oriented perspective, we sort of replace inheritance with delegation (`Switch` delegates to `Host`) and from a SQL perspective not much changes. We can even keep `id` as the column, which has the `FOREIGN KEY` constraint, instead of introducing a separate `host` column.

Switches wouldn't have their own IDs (not important) and we save us an extra column and `UNIQUE` index.
