### ISSUE TITLE
Can't create bank accounts

### ISSUE THREAD

**Issue by toothstone** [agdsn/pycroft#155]
Pressing "übernehmen" at https://pycroft.agdsn.de/finance/bank-accounts/create returns:
> werkzeug.routing.BuildError: Could not build url for endpoint 'finance.bank_accounts'. Did you mean 'finance.bank_accounts_list' instead?

**Comment by marcelb98** [comment]
Fixed with commit 74c31d6000d2ac575d9109c14dc49c66fa5ad008
