### ISSUE TITLE
Can't import CSV data

### ISSUE THREAD

**Issue by toothstone** [agdsn/pycroft#157]
When I try to import a CSV file, pycroft returns the following error:

> Fehler: Der CSV-Import ist fehlgeschlagen: Could not read CSV. Caused by: iterator should return strings, not bytes (did you open the file in text mode?)

**Comment by sebschrader** [comment]
The Python 3 migration most likely broke it silently.

**Comment by toothstone** [comment]
@sebschrader you mentionend that you started working on a new parser, could you push that to a branch/tell me where to find it?

**Comment by sebschrader** [comment]
The parser is not Pycroft related. It's for the treasurer's tools.
