### ISSUE TITLE
Use PostgreSQL's native timestamp range types for intervals

### ISSUE THREAD

**Issue by sebschrader** [agdsn/pycroft#160]
Since we no longer depend on SQLite we can fully embrace the feature set of PostgreSQL and implement timestamp intervals, used for memberships, with the native [range types](https://www.postgresql.org/docs/9.6/static/rangetypes.html).

The benefits are:
* leveraging PostgreSQL [operators and functions](https://www.postgresql.org/docs/9.6/static/functions-range.html) for these types
* ability to define (GiST) [indexes](https://www.postgresql.org/docs/11/rangetypes.html#RANGETYPES-INDEXING) on the range column to improve the membership lookup computation
* Ensure non-overlapping memberships with [exclusion constraints](https://www.postgresql.org/docs/9.6/static/ddl-constraints.html#DDL-CONSTRAINTS-EXCLUSION)

**Comment by lukasjuhrich** [comment]
We should discuss adding appropriate SQL-functions for adding and removing a membership to ensure that the database can be manipulated in an atomary manner without needing to consult the API.
Example use cases are manual intervention on the `psql` REPL or data imports.

The downside is that we would replicate yet another bulk of logic into the serialization layer.

**Comment by lukasjuhrich** [comment]
I'm not sure whether the last comment belonged here.

**Comment by lukasjuhrich** [comment]
- [ ] Add a decorator (de-)serializing into `Interval`s
- [ ] Add all the [operators](https://www.postgresql.org/docs/current/functions-range.html) we get for intervals (see [sqla docs](https://docs.sqlalchemy.org/en/14/core/custom_types.html#redefining-and-creating-new-operators))
- [ ] Use the decorated type in the `Membership` model

**Comment by lukasjuhrich** [comment]
Similar: #210

**Comment by lukasjuhrich** [comment]
Reopoening due to erroneous “merge”

**Comment by lukasjuhrich** [comment]
note: since GiST-indexes are postgresql-specific, we have to create indices manually: https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#index-types
