### ISSUE TITLE
Create a view to resolve the current group memberships/properites

### ISSUE THREAD

**Issue by sebschrader** [agdsn/pycroft#161]
To assist in #101 and probably lots of other things, we should create a view that resolves the group membership and/or properties at `CURRENT_TIMESTAMP`:

1. The group membership view would have an `user_id` and a `group_id` column.
2. The property view would have an `user_id` and a `property` column.

I'm not really convinced, that we need the first type of view however. It encourages people to look up groups instead of properties. Do you need the `group_id` for #101, @lukasjuhrich?

This should probably done together #160.

**Comment by lukasjuhrich** [comment]
I'm heavily in favor of 2. as well.

**Comment by lukasjuhrich** [comment]
FYI I'm trying to remember certain queries and their execution speeds in https://git.agdsn.de/snippets/19. Perhaps that'll be useful when examining the effect of turning on indices or switching to the range types (#160).

**Comment by sebschrader** [comment]
It would be great, if the view would allow you to distinguish between the cases:

1. Property is neither granted nor revoked
2. Property is granted and not revoked
3. Property is granted and revoked
4. Property is not granted and revoked

The first case is easy; no row is returned. The other three can be distinguished by having three different columns `granted`, `revoked`, and `effective ` (or a better name). The first two are simple existence checks and the third can be computed from the two others.

Most code will be interested in the `effective` column only, but in some cases (e.g. #101 or our UI), we do want to distinguish between 1, 3, and 4.
