### ISSUE TITLE
Provide rejected properties in view

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#170]
Properties that are currently not granted because they have been _rejected_ should also be made accessible in a view. Either we

- Extend `current_property` by a `type` column (`ENUM granted, rejected`) and modify all existing queries against that by adding `WHERE type=granted`
- Add a new view `current_rejected_property`

The first option is probably best, but requires the query to be slightly more complex.

A use case would be e.g. adding a „denied, reason unknown“ radius response group if `network_access` has been denied, but the person is technically a member and not just moved out.

**Comment by sebschrader** [comment]
This is basically, what I already proposed in #161, although my solutions are a bit different.
