### ISSUE TITLE
Create Views for Sipa

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#173]
In order to not duplicate too much of the model internals in Sipa, we should provide views for:

- [x] the current credit
- [ ] the traffic history, chunked in days, perhaps limited to seven days
- [ ] For each user's interface, the mac and a ", "-joined list of IPs
- [ ] The finance history (just date and amount)

Using this, sipa only needs to define `User`, `Room`, `Building`, `Interface`, the above views, and some pw-hashing-functionality.

**Comment by ibot3** [comment]
Couldn't it be also interesting to implement this with an API ( #6 )?

**Comment by lukasjuhrich** [comment]
On the other hand, creating an API has the advantage that one can be imperative and does not have to construct complicated queries like the credit history (note that you will need the traffic balance accumulated to _just before_ the seven days window in which you do a per-bucket-accumulation to get credit history and not only traffic usage) in pure SQL.
See my quck, dirty, unfinished and inexperienced attempt in `origin/sipa-api` I hacked together yesterday.

**Comment by lukasjuhrich** [comment]
Considering that the traffic limit will be obsolete in the course of the next months (or something in that dimension), one might consider just not supporting the traffic history at all in favor of a faster deployment.

**Comment by ibot3** [comment]
@Georgeto 
Calculating the correct traffic-history seems to be a bit more difficult. We may should meet IRL to evaluate/implement this together.

**Comment by toothstone** [comment]
This issue seems to be out of touch we the actual development work that has happened in the last weeks. @ibot3 would you be so kind to update this?

**Comment by ibot3** [comment]
Pycroft offers an API instead of the views that are described here. 
We should create a new issue if there are missing features in the API.
