### ISSUE TITLE
Retrieve bank account transactions via FinTS

### ISSUE THREAD

**Issue by ibot3** [agdsn/pycroft#182]
Pycroft should be able to retrieve new bank account transaction directly from the bank. This can be done using the Finance Transaction System (FinTS). There already exists a FinTS library for python that we could use: https://github.com/raphaelm/python-fints

**Comment by marcelb98** [comment]
I've started implementing this feature in the branch [payment](/agdsn/pycroft/compare/payment). After the financer has entered his credentials for the bank-account all potentially new transactions are fetched with FinTS. Potentially new are those transactions, which took place on the day of the last import or later. (So we still have to check each of these transactions if it's already imported.)

Why are we saving the (old) account number and bank code in `BankAccountActivity`? FinTS provides only IBAN and BIC.

Along the way I've fixed a bug which occurred while listing all existing bank accounts when one of those accounts hasn't had any transactions. Now 2018-01-01 is returned as the date of the last import for those accounts.

Furthermore, I've added a check to prevent users from creating two bank accounts with the same IBAN.

**Comment by ibot3** [comment]
And why do we need such a dummy date (2018-01-01)? Wouldn't it maybe better to handle None/Null entries correctly?

**Comment by marcelb98** [comment]
I think it's good to fetch the transactions starting with the day of the last import, because FinTS is only fetching transactions in an interval. If we start this interval with the date of the last import, we've already filtered out many transactions which are definitely imported.

The dummy date was just a quick fix.
