### ISSUE TITLE
Return inverted values for finance tables

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#185]
As discussed with various people, the inverted view should also display inverted values.

The finance tables already request the inverted view on certain occasions, however this only changes the value of `is_positive`. The json endpoint should use the negative of the values to provide a consistent view in e.g. the user status page.

The info text can be redacted to something along the lines of “this is the inverted view. in the system, positive values correspond to demands from the AGDSN to the user, not the credit a user has.”

**Comment by ibot3** [comment]
The amount at the bottom of the table is not inverted yet.
