### ISSUE TITLE
You can not move a user in the frontend

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#19]
> ### Redmine metadata
> Attribute | Value
> ------------ | --------
> done_ratio | 0
> status | New
> start_date | 2015/11/10
> created_on | 2015/11/10 23:35:21 +0100
> author | florian
> priority | Normal
> updated_on | 2016/09/18 19:59:38 +0200
> tracker | Bug
> asigned_to | None

---
Because of missing reverse_dns_zone in the imported data this function can not work. As soon as the data is imported correctly it should work fine.

--
_This issue has been automatically imported from redmine on 2016-09-28 19:08:26.635909_

**Comment by lukasjuhrich** [comment]
@sebschrader @mueslo Can you reproduce it? Is this still an issue?

**Comment by mueslo** [comment]
Just tested it, works for me

**Comment by lukasjuhrich** [comment]
Thanks @mueslo , closing.
