### ISSUE TITLE
Repair account typeahead on transaction creation page

### ISSUE THREAD

**Issue by ibot3** [agdsn/pycroft#193]
Creating a transaction is currently not easy possible with the UI, because the typeahead field for selecting the finance accounts is not working.

**Comment by ibot3** [comment]
@sebschrader 
You switched to an other typeahead version/fork in your downstream files.
Could you also take a look at this?

**Comment by sebschrader** [comment]
I'll take a shot at it on the weekend.

**Comment by ibot3** [comment]
The typeahead seems to work on the finance/bank-account-activities/XYZ page, but not for user accounts.
Further, `finance/transactions/create` cannot be accessed at all.

**Comment by ibot3** [comment]
And 31c51889f69c5e8815ca9f0d6f7e199707093cf2
