### ISSUE TITLE
Add birthdate attribute for users

### ISSUE THREAD

**Issue by ibot3** [agdsn/pycroft#194]
Every user needs a birthdate attribute. This has to be added to the model.
Methods for editing the birthday for a user need to be implemented in the UI.

**Comment by lukasjuhrich** [comment]
Since when is this important? Doesn't this violate the principle of data economy?

**Comment by MarauderXtreme** [comment]
It is necessary for providing the network access under current regulations iirc.

**Comment by ibot3** [comment]
https://www.gesetze-im-internet.de/tkg_2004/__111.html

The birthday of a user is currently stored on papers that wait to be destroyed. But this can only happen after we transferred the dates of birth into our user management system.

**Comment by toothstone** [comment]
> Every user needs a birthdate attribute.
Please note that this only applies to users with network access. A member doesn't need to supply a birthday, only if they apply for a network connection it needs to be recorded (as is done on our forms already).

**Comment by lukasjuhrich** [comment]
> Please note that this only applies to users with network access.

Ergo:
1. Make the column nullable
2. incorporate the optionality in the UI-workflow (e.g. if there were optional forms for people requesting network access and other people, one form should require the birthday, another should not)

**Comment by toothstone** [comment]
Given the recent GDPR troubles, we probably should implement TKG § 111(5) as well:

> (5) Die Daten nach den Absätzen 1 und 2 sind mit Ablauf des auf die Beendigung des Vertragsverhältnisses folgenden Kalenderjahres zu löschen.

Or we will have to set up a workflow to do that manually for Pycroft.
But I guess cleanup routines by now merit their own bundle of issues anyhow...

**Comment by lukasjuhrich** [comment]
@toothstone #67 is related
