### ISSUE TITLE
datetime.datetime not correctly parsable in log messages

### ISSUE THREAD

**Issue by ibot3** [agdsn/pycroft#200]
Creating a user creates two erroneous log messages.

Example:

> Parameter deserialization error: ValueError: unconverted data remains: .773001+00:00 in message: {"kwargs": {"group": {"type": "builtins.str", "value": "Mitglied"}, "during": {"type": "pycroft.helpers.interval.Interval", "value": {"upper_value": null, "lower_value": {"type": "datetime.datetime", "value": "2018-08-15T18:07:39.773001+00:00"}, "lower_closed": true, "upper_closed": false}}}, "message": "Added to group {group} during {during}."}

This could be a result of @Georgeto latest changes on the datetimes.

**Comment by ibot3** [comment]
I also found the following error message on a new user without a room set:

> File "/pycroft/web/blueprints/user/\_\_init\_\_.py", line 376, in user_show_logs_json
> TypeError: can't compare offset-naive and offset-aware datetimes

**Comment by Georgeto** [comment]
> I also found the following error message on a new user without a room set:
>> File "/pycroft/web/blueprints/user/__init__.py", line 376, in user_show_logs_json
>> TypeError: can't compare offset-naive and offset-aware datetimes

This should be already fixed by 27d32b8a7e818dd76c57f4554fbadc2a957ef364.

**Comment by ibot3** [comment]
I was on the newest commit on develop when I experienced this issue.
