### ISSUE TITLE
Table-fixed header is broken

### ISSUE THREAD

**Issue by Georgeto** [agdsn/pycroft#208]
![screenshot_20180819_000820](https://user-images.githubusercontent.com/9250103/44303575-36f61280-a344-11e8-9165-11df5cf7d4db.png)

![screenshot_20180819_000849](https://user-images.githubusercontent.com/9250103/44303574-365d7c00-a344-11e8-9908-b995ce451eea.png)

**Comment by ibot3** [comment]
I fixed that some time ago.
