### ISSUE TITLE
JavaScript Injection

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#21]
> ### Redmine metadata
> 
> | Attribute | Value |
> | --- | --- |
> | done_ratio | 0 |
> | status | New |
> | start_date | 2016/08/26 |
> | created_on | 2016/08/26 20:26:05 +0200 |
> | author | @sgeisler |
> | priority | High |
> | updated_on | 2016/09/18 19:06:41 +0200 |
> | tracker | Bug |
> | asigned_to | None |

---

For many actions (like blocking users) admins can add comments. These comments aren't getting filtered, so anyone can add JavaScripts. It's probably possible to steal sessions using malicious JavaScript.
## 

_This issue has been automatically imported from redmine on 2016-09-28 19:08:31.787267_

**Comment by jnsga** [comment]
Cannot reproduce

**Comment by lukasjuhrich** [comment]
Most likely fixed in dd77f5f48, 80219c355
