### ISSUE TITLE
Header on property group table is shifted to left

### ISSUE THREAD

**Issue by Paktosan** [agdsn/pycroft#213]
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/4009269/44308253-08168580-a3b2-11e8-97ee-c9c416fa36d0.png">

- Seen in Safari 12
- Does not happen in Chromium 68

**Comment by lukasjuhrich** [comment]
@Paktosan any updates? Can you reproduce this issue?

**Comment by Paktosan** [comment]
The issues still persist with Safari 13. For me this is no issue at all since I moved to Google Chrome. I am not really sure how I would debug that issue anyway since I am not really great at CSS. And it is a minor issue anyway.

**Comment by lukasjuhrich** [comment]
Closing as wontfix / CNR, reopening once someone else complains about it.

**Comment by Paktosan** [comment]
This actually seems not to happen anymore, just checked it.
I also vaguely remember you telling me that it is fixed a longer time ago.
