### ISSUE TITLE
TemplateSyntaxError when trying to create transaction

### ISSUE THREAD

**Issue by Paktosan** [agdsn/pycroft#214]
When calling http://0.0.0.0:5000/finance/transactions/create it throws an TemplateSyntaxError.
![pageshot of jinja2 exceptions templatesyntaxerror unexpected end of template jinja was looking for the following tags endblock the innermost block that needs to be closed is block werkzeug debugger 2018-08-00-1339 14](https://user-images.githubusercontent.com/4009269/44308397-4c575500-a3b5-11e8-9a37-90389517133f.png)

**Comment by lukasjuhrich** [comment]
For the future, note that you can click on the blue header bar to switch to a copy-and-pasteable view of the stacktrace.

**Comment by lukasjuhrich** [comment]
Perhaps this issue is „just“ a missing frontend test case verifying the template has correct syntax ;-)

**Comment by ibot3** [comment]
Closed with 308ddfaa3a771e1169f33f0f188ab734c0c1d6c8
