### ISSUE TITLE
Unclear check boxes when creating new member

### ISSUE THREAD

**Issue by Paktosan** [agdsn/pycroft#218]
<img width="333" alt="image" src="https://user-images.githubusercontent.com/4009269/44308478-0602f580-a3b7-11e8-9c63-a7a297f52077.png">
It is unclear what these check boxes are doing. Maybe we can add a mouseover to explain them?

**Comment by ibot3** [comment]
These should be hidden if no errors came up. The javascript for this is propably not working correctly anymore.

"Host annektieren" should appear if the MAC is already in use

"* Hinweise ignorieren" should appear for other errors (e.g. mail already in use)

**Comment by Paktosan** [comment]
I can confirm that there are Javascript errors on the site.
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/4009269/44308552-0f409200-a3b8-11e8-9e5c-b4a52a0bf0fe.png">

- Seen in Safari 12
- Also happens in Chromium 68

**Comment by ibot3** [comment]
The inputMacMask() function should be replaced by a new MACField.

**Comment by ibot3** [comment]
The javascript seems to work fine at https://pycroft.agdsn.de/user/create

**Comment by Paktosan** [comment]
I guess that the test instance is heavily out of date and no longer meaningful.

**Comment by lukasjuhrich** [comment]
@Paktosan do the issues still persist?

**Comment by ibot3** [comment]
Yes
