### ISSUE TITLE
Can't assign traffic group

### ISSUE THREAD

**Issue by Paktosan** [agdsn/pycroft#219]
While it is possible to create new traffic groups in the UI it does not seem to be possible to assign them to users.

**Comment by lukasjuhrich** [comment]
This is not a bug. Just like before, assigning non-default traffic groups is a task for `root` users. Changing that would be a design decision.

Marking this as `feature request`.

**Comment by JuKu** [comment]
We have detected that all users which was blocked during financial issues while importing them from userman don't have a traffic group assigned. So this is a really important for supporters to correct this behaviour.
