### ISSUE TITLE
Add autofocus to the first field of a form

### ISSUE THREAD

**Issue by ibot3** [agdsn/pycroft#257]
The first field of a form should be focused automatically. For single fields, this can be done with `render_kw={'autofocus': True}`.

**Comment by ibot3** [comment]
@sebschrader 
Do you have an idea how this could be implemented?

**Comment by toothstone** [comment]
I guess this was meant for @ibot3.

**Comment by lukasjuhrich** [comment]
It was indeed, sorry.
