### ISSUE TITLE
Email address verification

### ISSUE THREAD

**Issue by gehinz** [agdsn/pycroft#258]
Test newly added or changed user email addresses intended for forwarding emails before applying the change to the database.
1. Immediatly check for valid format. (Just to remove some obvious typos.)
2. Send a verification email. Wait for the activation via link.

Maybe also do this test once for all currently existing accounts to clean up the data.

**Comment by lukasjuhrich** [comment]
@ibot3 please consolidate this with the current state of things seeing that you implemented some verification system.

**Comment by ibot3** [comment]
Already implemented.
