### ISSUE TITLE
Show manufacturer of device based of OUI of mac address

### ISSUE THREAD

**Issue by wesx** [agdsn/pycroft#259]
It could be a good idea to show the most likly producer of the device based on the OUI of the mac address. A list of registered vendors and OUI can be found at http://standards-oui.ieee.org/oui.txt

**Comment by ibot3** [comment]
One could use the [ethercodes.dat](https://linuxnet.ca/ieee/oui/ethercodes.dat) file which has a better format (tab + space seperated).

**Comment by ibot3** [comment]
Or even better: https://github.com/coolbho3k/manuf

**Comment by toothstone** [comment]
The manuf readme states that there will be no updates to their database, and that one should use the built-in update function of manuf. I don't see this addressed so far?

I guess running `python manuf.py --update` during the pycroft build process would suffice.

**Comment by ibot3** [comment]
The update is done if the `manuf` file does not exist. I don't know if all files get deleted when deploying Pycroft. If that's not the case, the update command or just a delete command should be issued on deployment.

**Comment by lukasjuhrich** [comment]
AFAICS the prod docker image does not define any volumes, and neither does the prod docker compose file. Therefore any deployment of a new pycroft docker images does not know of any files associated with the older pycroft instance.
