### ISSUE TITLE
Hades logs time out

### ISSUE THREAD

**Issue by toothstone** [agdsn/pycroft#261]
I rarely get to see any hades logs, most of the time they time out.
On top of that displaying logs is laggy because the loader waits for the hades timeout.

**Comment by lukasjuhrich** [comment]
> On top of that displaying logs is laggy because the loader waits for the hades timeout.

If the logs aren't there, they aren't there. The existence of a tab for „all logs“ implies that loading the data for „all logs“ must wait for the hades logs to then sort them by time. They're already displayed asynchronously, at least more than rendering the table at response time.

Considering the hades logs, I that's most likely an issue on the hades side.

**Comment by Paktosan** [comment]
As far as I know, Hades logs are working for a while now. So I guess, we can close this issue?

**Comment by toothstone** [comment]
I guess so, seems to work fine, but I haven't worked that much with Pycroft lately.

**Comment by ibot3** [comment]
A temporary fix is described here: https://wiki.agdsn.de/index.php/Hades-Debugging

**Comment by lukasjuhrich** [comment]
Closing, since this hasn't come up in my latest pycroft sessions.

**Comment by ibot3** [comment]
This still happens, but is a problem in Hades.

**Comment by lukasjuhrich** [comment]
Ah, okay, please create one in the hades-repository if it does not yet exist.
