### ISSUE TITLE
Finish traffic credit handling

### ISSUE THREAD

**Issue by toothstone** [agdsn/pycroft#264]
In addition to the missing nightly credit recharge and handling the resulting suspensions, I would like to bump some more open issues: #130, #131, #175, #219 which probably should be addressed as well.

**Comment by lukasjuhrich** [comment]
I have to disagree at one point: #131 is everything but Urgent, and unlikely to be deployed in the near future. But thanks for creating a parent-issue.

**Comment by toothstone** [comment]
Yeah, the configurability is not urgent atm, but we need to ensure compliance with data protection regulations regarding the traffic logging asap.

**Comment by lukasjuhrich** [comment]
> asap

Why not just drop the traffic_volume table daily as currently the blocking scripts are not ready yet?

**Comment by toothstone** [comment]
> Why not just drop the traffic_volume table daily as currently the blocking scripts are not ready yet?

This is not really feasible from the support teams point of view, as traffic volume is a simple way to see if a connection is working, the current (unrelated) downtime of the pmacct system has already lead to some complains. Furthermore it would further increase confusion among users, so I would rather see a permanent solution. We will need one anyhow, completely independent from the existence or state of blocking mechanisms/rules.
