### ISSUE TITLE
Add OpenSearch Description

### ISSUE THREAD

**Issue by toothstone** [agdsn/pycroft#265]
I find the 'press Tab to search' feature very useful and would like to see it enabled for pycroft as well.

We'll need to add an OSD (https://github.com/dewitt/opensearch) for that.
Some good pointers are also given here: https://stackoverflow.com/questions/7630144/how-to-add-google-chrome-omnibox-search-support-for-your-site

**Comment by lukasjuhrich** [comment]
Rel: https://developer.mozilla.org/en-US/docs/Web/OpenSearch#opensearch_description_file
given example:
```xml
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/"
                       xmlns:moz="http://www.mozilla.org/2006/browser/search/">
  <ShortName>[SNK]</ShortName>
  <Description>[Search engine full name and summary]</Description>
  <InputEncoding>[UTF-8]</InputEncoding>
  <Image width="16" height="16" type="image/x-icon">[https://example.com/favicon.ico]</Image>
  <Url type="text/html" template="[searchURL]"/>
  <Url type="application/x-suggestions+json" template="[suggestionURL]"/>
  <moz:SearchForm>[https://example.com/search]</moz:SearchForm>
</OpenSearchDescription>
```

**Comment by FestplattenSchnitzel** [comment]
We have an OSD in place for accessing user IDs only.  Feel free to open a new issue for extending the existing one.
