### ISSUE TITLE
Password on user datasheet

### ISSUE THREAD

**Issue by LukasGibeh** [agdsn/pycroft#269]
The password printed on the user data sheet is formatted without serifs. Thus capital ```I``` and lowercased ```l``` are hard to distinguish especially when the printer is in "toner-saving mode".

Proposal: format password as monospace font

**Comment by toothstone** [comment]
For the record, passwords never contain `l` at the moment, see https://github.com/agdsn/pycroft/blob/develop/pycroft/helpers/user.py#L27
