### ISSUE TITLE
Improve ID recognition in payment description

### ISSUE THREAD

**Issue by toothstone** [agdsn/pycroft#274]
There are two recurring problems with real-world payment descriptions:

- dashes are missing (can not be entered or are not preserved when the transaction is received) (e.g. `12345 78`)
- additional spaces are introduced (probably in hand-written descriptions) (e.g. `12345 -78`)

So I would propose the following:

- for matching, strip the description of spaces
- if the description starts with 6 or 7 digits, check for type 2 conformity and parse as ID

Maybe @wesx has some more recommendations.

**Comment by toothstone** [comment]
We should probably also strip the description of `/` and similar separator chars.

**Comment by ibot3** [comment]
@marcelb98 Could you take a look at this?

**Comment by toothstone** [comment]
Quote vincent.knyrim (https://mm.agdsn.de/agdsn/pl/4kqzj9cqkbfrpp9woaht9tn13c):

> Das Problem wurde ziemlich sicher schon festgestellt, aber es tritt gerade wieder akut auf:
> Beim Beitragsüberweisungsmatching werden viele anhand der ID eindeutig zuordenbare Überweisungen nicht zugeordnet, weil innerhalb des ID-Strings was unwichtiges kaputt ist:
> 
> * Leerzeichen statt Bindestrich
> * gar kein Trennzeichen
> * Zeilenumbruch oder so
> 
> Das beim Matching zu erkennen sollte doch wirklich nicht viel Arbeit sein.
> Derzeit wird das oft erst auf Nachfrage erkannt und muss dann mit dem doch etwas aufwändigen Informations/Berechtigungs-Workflow behoben werden.
> 
> Deshalb meine Bitte: Erledigt das zeitnah.
> 
> Wenn das vor der nächsten Finanzsperrung funktioniert, geb ich dem verantwortlichen Menschen ein Getränk (im NOC) aus – evtl. auch etwas mehr.

**Comment by marcelb98** [comment]
done: 2c7d3ad
