### ISSUE TITLE
Calculates membership changes based on finanz data also for members of group ausgezogen

### ISSUE THREAD

**Issue by wesx** [agdsn/pycroft#275]
Currently the "calculate membership changes" ignore people in the group "Ausgezogen". This leads to some people which are still members but have a balance of -60€ and not shown in the preview of changed memberships.

**Comment by ibot3** [comment]
The main problem is that they are both, "Mitglied" and "Ausgezogen". This shouldn't be the case. Removing the membership in the "Ausgezogen" group should solve the problem.
