### ISSUE TITLE
Wrong subnet after room-change

### ISSUE THREAD

**Issue by Floyer007** [agdsn/pycroft#277]
There is a big problem regarding subnets.
We have one domitory which has two subnets.
If a user is moving within this domitory from a room with subnet-A to a room with subnet-B, the subnet will result in subnet-A.
Therefore no DHCP-leases will be possible.

There is also a problem for the inversed case.
One subnet for different domitories.

**Comment by sebschrader** [comment]
I'm not sure about the inverse case, it seems to work fine in ZW41.

**Comment by Floyer007** [comment]
Okay, I just catched it out of the conversation between members.

**Comment by mmarx** [comment]
In the dual case, it will still assign a new IP in the same subnet, which will not cause any problems, but is unnecessary.
