### ISSUE TITLE
Add "fast moveout" button on "overcrowded rooms" page

### ISSUE THREAD

**Issue by ibot3** [agdsn/pycroft#278]
We may want to have a button for a fast moveout for overcrowded rooms.

**Comment by toothstone** [comment]
Wouldn't a "quick delete host" button be better for this use case?
We don't want to cancel a membership or anything, we only need to free addresses.

**Comment by ibot3** [comment]
We don't want to cancel the membership. But we can move out a user without cancelling the membership.

**Comment by lukasjuhrich** [comment]
AFAICS you still want to move out the _hosts_ of the user, if the user itself lives there (or anywhere, for that matter) is irrelevant. So @toothstone's point still stands.

**Comment by ibot3** [comment]
I think this isn't really needed or wanted.
