### ISSUE TITLE
Update fee logic

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#28]
> ### Redmine metadata
> 
> | Attribute | Value |
> | --- | --- |
> | done_ratio | 0 |
> | status | New |
> | start_date | 2016/03/10 |
> | created_on | 2016/03/10 01:14:09 +0100 |
> | author | @mueslo |
> | priority | High |
> | updated_on | 2016/09/18 19:13:31 +0200 |
> | tracker | Feature |
> | asigned_to | None |

---

Since the fee regulations decision on 2016-03-09, it no longer makes sense to have reduced fees and semester fees, only regular fees (and fee exemptions/reductions).

However, there might be some use in retaining the fee information/logic for past semesters.
## 

_This issue has been automatically imported from redmine on 2016-09-28 19:09:00.865106_

**Comment by ibot3** [comment]
Closed with #179
