### ISSUE TITLE
Catch error messages

### ISSUE THREAD

**Issue by gehinz** [agdsn/pycroft#288]
Cryptic sql exceptions are annoying.
Extract important information (at least for known errors) and present them in a more human friendly way.
Known errors that should be dealt with this way:

- [x] MAC address already exists in System (when editing an interface)

**Comment by lukasjuhrich** [comment]
@gehinz are there still messages that annoy you, or can this issue be closed?

**Comment by lukasjuhrich** [comment]
Given a lack of reaction and that currently we catch most things in most cases, I would like to close this.
