### ISSUE TITLE
Duplicate login notice

### ISSUE THREAD

**Issue by JuKu** [agdsn/pycroft#290]
Sometimes there is a duplicate login notice:
![dd](https://user-images.githubusercontent.com/1138046/48740205-ce764480-ec56-11e8-9c10-f079e15c936b.PNG)

**Comment by lukasjuhrich** [comment]
Because
1. this is not particularly painful and
2. noone brought this up in two years (or came up with a way of reproducing this)

I'm going to close this, as it has no chance of getting fixed if it even still exists.
