### ISSUE TITLE
Add duplicate account check with Abe

### ISSUE THREAD

**Issue by Lodifice** [agdsn/pycroft#303]
There should be no duplicates in Pycroft's unix accounts and Abe's account names. Since pycroft and abe are both schemas in the usermanagement database, implementation can directly use the database (there are only a few accounts in Abe's LDAP which are not in the database). A possible implementation is a trigger on insert, but maybe there are cleaner solutions.

**Comment by ibot3** [comment]
I created a constraint trigger.
