### ISSUE TITLE
Write Abe import script

### ISSUE THREAD

**Issue by Lodifice** [agdsn/pycroft#304]
As the Abe import will be run against the production system, an import script shall be created which allows local testing. It should also have sufficient logging of what happens in order to avoid import fails. The Gerok importer may serve as a good starting point.

**Comment by lukasjuhrich** [comment]
The current schema appears to look as follows (generated by `schemaspy`):

![abe_schema](https://user-images.githubusercontent.com/10060406/66268915-69ade380-e842-11e9-94df-2eb2fc708730.png)

**Comment by lukasjuhrich** [comment]
See the corresponding [gitlab Repository](https://git.agdsn.de/AGDSN/pycroft-abe-importer)

**Comment by lukasjuhrich** [comment]
Update: It has been transferred to [agdsn/abe-importer](https://github.com/agdsn/abe-importer/) to enable a [common project board](https://github.com/orgs/agdsn/projects/1).
