### ISSUE TITLE
Add page that shows transactions created by non-treasurers

### ISSUE THREAD

**Issue by ibot3** [agdsn/pycroft#318]
There should be a page that shows all transactions that were created by non-treasurers. This should allow the treasurers to check transactions that were f.e. created by supporters when a bank account activity was required to be matched manually.

**Comment by Paktosan** [comment]
As treasurer, I do not want non-treasurers to be able to create transactions.

**Comment by LukasGibeh** [comment]
@Paktosan I would appreciate if there was some further discussion on this topic. 

I would consider the option to match transactions by non-treasurers a good idea (just the matching of membership fees and no purchase transactions etc.). Especially in May and November, coping with the huge amount of transactions has often not been easy for our treasurers in recent years, to my knowledge.

By adding a page as suggested by @ibot3 or appropriate logging, misuse can easily be prevented.

This procedure would also simplify our current workflow for both parties - support and treasurers.

**Comment by ibot3** [comment]
A discussion resultet in the following suggestion:

* Transactions get a new property "confirmed" that only treasurers can set to `true`.
* Non-treasurers can match unassigned transfers (membership contributions) to accounts. The resulting transaction is not "confirmed".
* The new page should list all currently non-"confirmed" transactions. For treasurers there should be two buttons at each entry:
** "confirm": The transaction becomes "confirmed".
** "revert": The transfer becomes unassigned again.
In both cases the transaction should disappear from the list.
