### ISSUE TITLE
Fix navbar

### ISSUE THREAD

**Issue by sebastl** [agdsn/pycroft#327]
Make navigation bar sticky.

**Comment by MarauderXtreme** [comment]
This is not a good fix for this. `position: sticky` is only fully supported in Firefox and Safari. Every other Browser only has partial support or prefixed support.

**Comment by mmarx** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/CSS/position#Browser_compatibility, everything except for IE and possibly mobile Safari should be fine; and only Safari seems to require a prefix.

**Comment by sebastl** [comment]
I added the webkit prefix and now browser support should be sufficient. Since all browsers not supporting `position: sticky` will ignore it and fall back to static positioning, I think it's a proper solution.

**Comment by lukasjuhrich** [comment]
Agreed. Since there is only one current browser (in particular, IE, which we don't care about when we look at the pycroft user base) that does not profit from that solution, but on the other hand, the changes don't make anything _worse_ if you're on that browser, I think this is an appropriate fix.
