### ISSUE TITLE
Make user's address editable

### ISSUE THREAD

**Issue by ibot3** [agdsn/pycroft#347]
It should be possible to edit a users address in the UI.

With #338, the option to create a user without moving the user into a room has been removed. This should be possible again. Users without a room could get a dummy address by default.

**Comment by lukasjuhrich** [comment]
Plan:
- [ ] Add `edit_address` function to `lib`
- [ ] Add tests for all the scenarios (with / without room / previous address set)
- [ ] Implement the lib functionality
- [ ] Allow for address editing in UI, and ensure addresses are represented whenever they differ from a user's room
