### ISSUE TITLE
Link to transaction details "disabled"

### ISSUE THREAD

**Issue by gehinz** [agdsn/pycroft#358]
After a transaction without any `Description` or `End-to-end` reference is assigned to an user account, the link text for the transaction details is empty.
Thus, in tables of transactions the link is not usable.

Example here: https://pycroft.agdsn.de/finance/accounts/7265

**Comment by lukasjuhrich** [comment]
Well spotted, that's a good hands-on introductory task for anyone interested tomorrow.
