### ISSUE TITLE
Versenden von Systemmails

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#37]
> ### Redmine metadata
> 
> | Attribute | Value |
> | --- | --- |
> | done_ratio | 0 |
> | status | New |
> | start_date | 2012/06/30 |
> | created_on | 2012/06/30 23:10:57 +0200 |
> | author | @cooox |
> | priority | Normal |
> | updated_on | 2016/09/18 19:01:54 +0200 |
> | tracker | Feature |
> | asigned_to | None |

---

Metaissue
## 

_This issue has been automatically imported from redmine on 2016-09-28 19:09:38.133288_

**Comment by lukasjuhrich** [comment]
> ### Redmine metadata
> Attribute | Value
> ------------ | --------
> created_on | 2012/06/30 23:28:13 +0200
> user | @janLo


---
Ich denke diese Aufgabe sollten wir bis hinter die Version 0.1 verschieben. Ich möchte hier auch gern noch einmal über die Möglichkeiten zur asynchronen Jobverarbeitung sprechen. Im Kopf habe ich so etwas wie eine "Celery":http://celeryproject.org/ Task queue, die sowohl mit dem Frontend, als auch dem Script backend (wie auch immer dieses getriggert werden soll) interagiert.

--
_This comment has been automatically imported from redmine on 2016-09-28 19:09:40.761513_

**Comment by lukasjuhrich** [comment]
War ehemals ein Meta-Issue. De facto ein Parent für #23 #59 #174

**Comment by ibot3** [comment]
Aber direkte Verweise gibt es ja nicht.
#267 schien mir jetzt als etwas erhaltenswerter von den beiden.
