### ISSUE TITLE
Flickercode support / TAN input

### ISSUE THREAD

**Issue by Paktosan** [agdsn/pycroft#375]
Since PSD 2, reading requests via FinTS may require a TAN to complete so we require a way to enter it in Pycroft. The flow would be the following:
1. User starts action involving FinTS
2. If TAN is required goto 3, else 5
3. User gets redirected to page showing Flickercode and input for TAN
4. If TAN is correct goto 5, else goto 3 and show message to try again
5. Action completes

For this to work we require some kind of session storage so we can save some data of FinTS library while the user enters the TAN.

**Comment by lukasjuhrich** [comment]
What is the current workflow? As far as I know, the flickercodes have been deprecated in favor of QR codes, correct?

**Comment by ibot3** [comment]
I think this can be closed.
There is no TAN required when the online banking login has been unlocked once within the last (60?) days.
So the workflow is to login to the online banking portal if a TAN is required.

**Comment by lukasjuhrich** [comment]
Closing this and PR #376, consequently.
