### ISSUE TITLE
Vendor field covers MAC address in MAC field

### ISSUE THREAD

**Issue by deepshitgoeshere** [agdsn/pycroft#378]
The new MAC vendor lookup tool we had to switch to doesn't use short names like the old one. As a result the vendor field next to the MAC address effectively covers the complete address, making it unreadable.

**Comment by Paktosan** [comment]
Maybe just write it below the input field?

**Comment by deepshitgoeshere** [comment]
@Paktosan That was our idea too, however I am still looking for a non-shitty-looking solution.
