### ISSUE TITLE
Require acknowledgement for failed tasks.

### ISSUE THREAD

**Issue by willimei** [agdsn/pycroft#380]
Write an email to the admins in case of failed Tasks. 
Thereby failed tasks will be noticed and resolved earlier.

**Comment by ibot3** [comment]
Probably a specific part of #267

**Comment by lukasjuhrich** [comment]
A simpler, but sufficient fix would be implementing an acknowledgement mechanism: the list of executed tasks gives no way of determining which of the failed tasks had a good reason (like someone executed this action earlier during the office hours not noticing the task), or which require attention.

We could then place the information „N failed, unacknowledged tasks“ somewhere prominent (i.e. everybody sees this on every login), giving this topic essentially enough attention.

**Comment by ibot3** [comment]
The email notification has been implemented. However, an ack would be better, as lukas said. So I will rename the issue.
