### ISSUE TITLE
User status icon for "internet access"

### ISSUE THREAD

**Issue by LukasGibeh** [agdsn/pycroft#383]
Currently, the "status icon for internet access" (next to the user's name on the page "Nutzer anzeigen") is "green" even when the user hasn't got an assigned IP address.

However, the status should just be "good", if there is a host and interface for the user.

**Comment by ibot3** [comment]
As the users mostly always have wifi access, it's not that wrong. But one could make the icon orange (warning), if there is wifi access, but no cable access configured.
