### ISSUE TITLE
Update information on wifi data sheet

### ISSUE THREAD

**Issue by ibot3** [agdsn/pycroft#390]
The information on the wifi datasheet is outdated.

**Comment by lukasjuhrich** [comment]
[Quick link to source](https://github.com/agdsn/pycroft/blob/c9ccec7afcd563cd7e07ebdbfa3275066d3d2da5/pycroft/helpers/printing/__init__.py#L32)

What points specifically?

**Comment by marcelb98** [comment]
The SSID and the link to our website are outdated. Starting on line [359](https://github.com/agdsn/pycroft/blob/c9ccec7afcd563cd7e07ebdbfa3275066d3d2da5/pycroft/helpers/printing/__init__.py#L359).
