### ISSUE TITLE
Too large UI

### ISSUE THREAD

**Issue by Paktosan** [agdsn/pycroft#391]
After the update to the new Bootstrap release, everything became bigger, almost comically large.
While a large UI is beneficial when used on touch devices, it feels out of place and also hides information simply by pushing it out of the viewport.
So I think we should scale down the complete UI to around 80-90 percent of the current size.

**Comment by lukasjuhrich** [comment]
Well… the font size actually didn't change that much. Most space changes stem from growing margins and paddings. „Just scale it down“ to compensate would make the font smaller, which IMO is at a good size at the moment. It's not that simple.

**Comment by lukasjuhrich** [comment]
It would be beneficial to adress specific pain points locally. Since we don't really systematically design anything, a lot of problems should be easily fixable by removing unnecessary information or restructuring things a bit.

**Comment by ibot3** [comment]
I already tried to reduce the font size some days ago which was not that bad.
IMO one problem are the table rows which seem to be noticeable higher than before.

**Comment by lukasjuhrich** [comment]
@Paktosan is that still relevant? IIRC that was related to the BS4 upgrade and were resolved by upgrading to BS5

**Comment by lukasjuhrich** [comment]
Closing due to lack of negative reply.
Note that safari compatibility is an unrelated (and `WONTFIX`) issue.
