### ISSUE TITLE
Add option to print the wifi datasheet without resetting the password

### ISSUE THREAD

**Issue by ibot3** [agdsn/pycroft#399]
New WiFi passwords are stored without hashing them, which makes it possible to display them afterwards.
There should be an option to display the WiFi datasheet again, without resetting the password.

@marcelb98 Could you take a look at this?

**Comment by marcelb98** [comment]
I think we don't need this leak of personal data to all of our supporters, since our members are able to see their wifi password after logging in on our webpage/sipa.
