### ISSUE TITLE
Remove explicit unicode string typing

### ISSUE THREAD

**Issue by ibot3** [agdsn/pycroft#404]
There are still lots of code parts where the `u"string"` notation is used, even though it is unnecessary in python 3.

We should remove the "u" prefixes in the whole project.

**Comment by lukasjuhrich** [comment]
I don't think that deserves an issue to be frank, this does not really have a visual impact.
In particular, a commit bulk-replacing all those literals would be way more noisy (e.g. breaking `git blame`) than beneficial.

**Comment by Georgeto** [comment]
I am in favor of getting rid of the unnecessary `u` prefixes,  and I don't think that hindering `git blame` is a good enough argument to block such a change.

**Comment by MarauderXtreme** [comment]
Regarding ignorerevs.

Since git 2.23.0 you can define a file where you collect all the Revs/SHAs that should be ignored.
`git config blame.ignoreRevsFile`
That makes it even more convenient. You could fix various things in atomar commits and still not clutter the history.

**Comment by lukasjuhrich** [comment]
We can also establish a [`pre-commit`](https://pre-commit.com/index.html#usage) setup and use the [`pyupgrade` hook](https://github.com/asottile/pyupgrade). It removes unicode literals, but also _way_ more!

**Step 1**
Commit a `.pre-commit-config.yaml` with the following contents:
```yaml
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
    -   id: pyupgrade
        args: ["--py39-plus"]
```

**Step 2**

Do a `pre-commit run --all-files` for a clean swipe, commit the changes, and introduce a `blame.ignoreRevsFile` like @MarauderXtreme said
