### ISSUE TITLE
Membership fee booking

### ISSUE THREAD

**Issue by willimei** [agdsn/pycroft#407]
The membership fee creation function checks if there was any transaction to the 'Beiträge' account within the whole month. This can lead to missing membership fees if any transaction (e.g. correction posting) have been done within that month.

To avoid this unexpected behavior the booking date and the description should also be checked.

**Comment by ibot3** [comment]
I would fix this by checking if the amount on the fee account side is negative. And only if that's the case, a booking will be considered as existing.
The fee booking should cover all usual cases, but not the special cases. That's the reason why it simply does nothing if a booking exists in the fee timespan. Fee bookings can also be done manually, if it is a special case and the booking mechanism does not consider the user.
