### ISSUE TITLE
Locking a User: duplicate logs

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#47]
> ### Redmine metadata
> 
> | Attribute | Value |
> | --- | --- |
> | done_ratio | 0 |
> | status | New |
> | start_date | 2016/02/02 |
> | created_on | 2016/02/02 02:34:33 +0100 |
> | author | @lukasjuhrich |
> | priority | Low |
> | updated_on | 2016/09/18 19:38:42 +0200 |
> | tracker | Bug |
> | asigned_to | None |

---

Locking a user results in two log messages.
## 

_This issue has been automatically imported from redmine on 2016-09-28 19:10:23.158672_

**Comment by mueslo** [comment]
This is in some ways intended. Suspending a user adds him to a certain group (which always results in a log entry), but this does not contain the reason, so that's why a second message is necessary.

**Comment by lukasjuhrich** [comment]
This has been fixed in 85aa9fc7cc6ec1dbd30b2f6c369575555c92e6a2.
