### ISSUE TITLE
Set time for planned relocation task

### ISSUE THREAD

**Issue by willimei** [agdsn/pycroft#488]
It would be nice of you can adjust the time for a task manually.
The physical movement from one dorm to another happens at day time. So it would be nice if you can schedule the relocation task for 12:00. Than you still have a working connection in the morning when you move out of your old room and also in the evening when you are at the new room.

**Comment by ibot3** [comment]
Depends on #83

**Comment by lukasjuhrich** [comment]
@willimei in light of the fact that datetime fields will not be available for a while (see the discussion in #83), I propose a quickfix by adding an optional `time` field for relocation tasks. Would that be enough, or is the timing important for other procedures as well?

**Comment by willimei** [comment]
> @willimei in light of the fact that datetime fields will not be available for a while (see the discussion in #83), I propose a quickfix by adding an optional `time` field for relocation tasks. Would that be enough, or is the timing important for other procedures as well?

I think this will be enough for the moment.
Other tasks like new memberships and end of memberships does not need this accuracy. For this it does not matter if they start a whole day earlier/later.
