### ISSUE TITLE
Improve room page

### ISSUE THREAD

**Issue by ibot3** [agdsn/pycroft#496]
The page showing details to a specific room could be improved:

- [x] Also display users that lived in the room in the past (using the `RoomHistory`) → #483 
- [x] The patchports could be listed side-by-side to save some space. Also there could be some kind of box around a patchport, to make clear which information belongs to a patchport.
- [ ] Switch position of room level and room number
- [x] Show rental agreements for the room

**Comment by lukasjuhrich** [comment]
The second point has been done by #664.

What precisely do you mean by „Switch position of room level and room number“?

**Comment by lukasjuhrich** [comment]
Last thing fiexd by #698.

**Comment by lukasjuhrich** [comment]
What is meant by “switch position of room level and room number”? Is this here not correct?
![image](https://github.com/agdsn/pycroft/assets/10060406/9225b55d-d52d-445f-8b1f-45a22b343f61)

**Comment by ibot3** [comment]
I don't remember anymore. Maybe this has been already fixed or something.
Current state looks good for me.
So this can be closed if there aren't further points.

**Comment by lukasjuhrich** [comment]
I think it might have been referring to [this](https://github.com/agdsn/pycroft/commit/5567a54f4814c81497657c112044534b34f695c0#diff-c8008556dd7d250c0a34f5b07df78a1743dbce4232a4f573e2975a7b198a6fc6L34-L37), which has been removed in 5567a54f, anyway.
