### ISSUE TITLE
Deprecate "User > Register" botton

### ISSUE THREAD

**Issue by chlewe** [agdsn/pycroft#497]
The registration of new users now happens exclusively via the online form on agdsn.de or via the "pending registration" tab on pycroft. Meanwhile, the button "User > Register" is deprecated and it is easy to mistakenly click it _(like I have today)_. The button should be explicitly marked as deprecated _(and maybe moved to as less prominent location)_ to prevent future accidents.

**Comment by gehinz** [comment]
I suggest the following Menu structure:
1. Übersicht
2. Mitgliedschaftsanfragen
3. Suchen
4. Anlegen (freie Adresseeingabe) (former "Anlegen (Extern)")
5. Anlegen (Extern/IBR) (former "Anlegen")
6. Archivierbar

As we won't add members by hand but might add people that where missing in an import and are entitled to Internet by Rental (now called Extern in Pycroft) we should make clear what the difference between the two "Anlegen" Functions is.
