### ISSUE TITLE
Integrity error on member creation

### ISSUE THREAD

**Issue by toothstone** [agdsn/pycroft#55]
Wenn adding a new member, one occasionally encounters the following error:

> IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.IntegrityError) duplicate key value violates unique constraint "dns_name_zone_id_name_key"
> DETAIL:  Key (zone_id, name)=(1, 1) already exists.
>  [SQL: 'INSERT INTO dns_name (name, zone_id) VALUES (%(name)s, %(zone_id)s) RETURNING dns_name.id'] [parameters: {'name': '1', 'zone_id': 1}]

**Comment by mueslo** [comment]
I think this is related to the way the legacy importer creates DNS names and zones.

**Comment by lukasjuhrich** [comment]
@mueslo what about DNS in general - do we need this abstraction in the schema? I somewhat thought we could erase this part completely, since the previous assumption of Pycroft Managing DNS was not up to date anymore.

**Comment by toothstone** [comment]
Maybe this is a duplicate of - or at least related to - #29?

**Comment by mueslo** [comment]
Is there a way to reliably reproduce this? Currently adding members works fine for me.

**Comment by lukasjuhrich** [comment]
@mueslo try it a second time with a different facility. I don't know whether the repetition or the selection of the facility caused it, but doing it a second time usually threw the error up.
