### ISSUE TITLE
Add list of tenancies to relocation dialog

### ISSUE THREAD

**Issue by gehinz** [agdsn/pycroft#555]
Currently the tenancies of a user are only displayed on the main page but not when entering in a movement via the move dialog. While entering the data it would be really helpful to find all the info regarding the old and new tenancies right below the move dialog.

**Comment by lukasjuhrich** [comment]
BY „tenancies of the user“, do you mean the StuWe rental contracts?

**Comment by lukasjuhrich** [comment]
(yes, he does.)
