### ISSUE TITLE
Include convenient links in quicksearch

### ISSUE THREAD

**Issue by toothstone** [agdsn/pycroft#58]
Some search terms (e.g. names like "Meier", "Müller", "Nguyen"...) will result in several dozen results, which are currently not displayed.

**Comment by toothstone** [comment]
/user/search actually already solves this.

**Comment by mueslo** [comment]
pagination on the quick search bar would still be very useful, though

**Comment by toothstone** [comment]
Or at least a fast way to switch to /user/search if the quick search is not sufficient.

**Comment by lukasjuhrich** [comment]
@toothstone I agree that the search is rather hidden, there should definitely be at least a link to the extended search on the quick search menu. → Reopening but renaming.

If anyone has more specific ideas (pagination etc.) feel free to suggest them.
