### ISSUE TITLE
Enable selection of multiple (not all) unconfirmed transactions for deletion / confirmation

### ISSUE THREAD

**Issue by FestplattenSchnitzel** [agdsn/pycroft#596]
Here: https://pycroft.agdsn.de/finance/transactions/unconfirmed

**Comment by lukasjuhrich** [comment]
This should not be too complicated. Bootstrap-table supports checkboxes: https://examples.bootstrap-table.com/index.html#methods/get-selections.html

The gist is:
1. You add a column like `<th data-field="state" data-checkbox="true"></th>`
2. You extract the selected rows with `getSelections`: `document.getElementById('table').bootstrapTable('getSelections')`
3. You issue a manual post request

Not sure if this is the most idiomatic way, but this is what I got from 5min of research.
