### ISSUE TITLE
Bank account transaction import: Catch and display exception on error

### ISSUE THREAD

**Issue by FestplattenSchnitzel** [agdsn/pycroft#613]
https://pycroft.agdsn.de/finance/bank-accounts/import

Currently, only the following is displayed:

> 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

That's not a meaningful error message that makes it hard to tell what exactly went wrong.  Displaying the exception name, message would be a huge improvement already.

**Comment by FestplattenSchnitzel** [comment]
Relates to https://github.com/agdsn/pycroft/issues/529 .

**Comment by lukasjuhrich** [comment]
@FestplattenSchnitzel I think this issue qualifies as a duplicate, since we want to catch the fints base extension there.
