### ISSUE TITLE
Task scheduling

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#62]
Pycroft should be able to execute asynchronous tasks at a given time.

This is not necessary for suspending a membership thanks to the intervalled membership logic, but for things like changing the mac address or the room a user lives in, schedule execution at a given time would drastically improve things for our members.

**Comment by mueslo** [comment]
An alternative to Celery might be https://github.com/agronholm/apscheduler

**Comment by ibot3** [comment]
> This is not necessary for suspending a membership thanks to the intervalled membership logic

That's not true. All hosts of a user need to be deleted and the room must be set to `None`.
