### ISSUE TITLE
Remove DNS management

### ISSUE THREAD

**Issue by lightning1** [agdsn/pycroft#72]
The whole dns management in pycroft is just overhead, since we are not able to make changes to our upstream dns. The model my be great, but it doesn't help us at all.

It should be removed.

**Comment by lukasjuhrich** [comment]
Let me formulate the following idea:
- remove `DNSZone`, `DNSName`, `*Record` relations
- Replace the thus obsolete `{primary,reverse}_dns_zone_id` ForeignKeys of `Subnet` by a simple domain name (str)

Apart from the latter ForeignKeys, nothing else in the model depends on said relations.

As we do not intend to manage any authoritative DNS information by the pycroft model, neither for servers nor for users, we can strip it down to purely informational entries such as the domain name for the subnets.

@lightning1 please correct me if I forgot something.

**Comment by sebschrader** [comment]
The subnets no longer need domain names, this can be stripped also.
