### ISSUE TITLE
Revisit importer's TODOs

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#75]
In the importer, more specifically in the [translate.py](https://github.com/agdsn/pycroft/blob/develop/legacy/translate.py), there are a lot of `# TODO` comments. These should be looked over and converted into Github issues, since bugs in the importer _must_ be resolved before the first deployment.

**Comment by lukasjuhrich** [comment]
Although a bit verbose, these are the comments `ag` found in `legacy/translate.py`:

```
legacy/translate.py
28:# TODO: missing or incomplete translations for status/groups/permissions, patchport, traffic, incidents/log, vlans, dns, ...
95:    #TODO: create other groups
113:    # todo import userman.log
114:    # todo think of best way to import zih_incidents
279:    # TODO: look over this
310:    # TODO: Think about this, this is a pretty unstable/volatile way to do things,
405:            other_account_number="NO NUMBER GIVEN", #TODO fill these properly, somehow
406:            other_routing_number="NO NUMBER GIVEN", #TODO
407:            other_name="NO NAME GIVEN", #TODO
428:    # TODO write-offs? write off mail memberships, but not full fees
429:    # TODO reconstruct past memberships based on fees incurred
430:    # TODO inspect 4000 transaction on 10538
493:    # TODO: note, missing transit, server and eduroam subnets
580:        # TODO insert proper patch_port names
596:        network_access_group=g_d["member"],  # todo: actual network_access_group
```

- L28 this is extremely generic and can probably ignored
- L95 The only groups we _could_ import would be the ones from the atlantis-LDAP
- L113 the userman log consist of one of the following messages: `gid change for uid $uid`, `gesperrt, nicht bezahlt`, `test`, and one actually meaningful message. I suggest we drop this information.
- L114 the last `zih_incidents` entry was from 2015-10. I suggest we also don't import this. (keeping in mind that we will keep a full backup of all legacy databases, anyway)
- L279 is just the question of @mueslo whether his compiled list of all our accounts and their types is correct.
- L310 the importer never crashed and after its only productive execution, it will be burned in the dooms of ~hell~ ~mordor~ ~hades~ something hot, so we don't care
- L405+ since this probably concerns the physical person and real-world bank account dual to this transaction, we don't have a possibility to fill these. (is this correct @sebschrader ?)
- L428 Whether or not we want to save these things is planned to be discussed after we got a working pycroft instance, but this issue is quite orthogonal
- L429 has been resolved already
- L430 probably has been resolved, because there is no user with that many transactions.
- L493 For what do we need the `transit, server, and eduroam` subnets, @sebschrader ? Doesn't sound like anything mission-critical to me.
- L580 This is indeed missing.
- L596 Is irrelevant except for edge cases, because everyone with `network_access` is also a `member` (at least in the “new” constitution of 2015(?)).

**Comment by sebschrader** [comment]
We do have the data as CSV in various formats, the bank changed it over the years, from 2006 on for the Wundtstraße division, so you'll never get a complete data set.

It's only worth the effort for the recent years.
