### ISSUE TITLE
Gestaltung des Nutzerdatenblatts

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#8]
> ### Redmine metadata
> 
> | Attribute | Value |
> | --- | --- |
> | done_ratio | 0 |
> | status | New |
> | start_date | None |
> | created_on | 2012/04/01 11:44:33 +0200 |
> | author | @cooox |
> | priority | High |
> | updated_on | 2016/09/18 18:54:58 +0200 |
> | tracker | Feature |
> | asigned_to | None |

---

_Rel. Jans E-Mail 1. April_

> > (vielleicht auch: den tollen, weißen Zettel mit den
> > paar Daten mal mit so ner Anleitung versehen?! 
> > Irgendwer wollte da mal noch Informationen mit drauf drucken und hat
> > dann nach einer Woche JUserman-Code lesen entnervt aufgegeben (zumal das
> > Repo seit einer Weile kaputt ist). Das wär aber definitiv ein
> > Feature-Request für die neue Nutzerverwaltung.
## 

_This issue has been automatically imported from redmine on 2016-09-28 19:07:13.663750_

**Comment by lukasjuhrich** [comment]
> ### Redmine metadata
> Attribute | Value
> ------------ | --------
> created_on | 2016/09/10 20:32:49 +0200
> user | @lukasjuhrich


---
It appears l3nkz has a non-pushed branch that seemingly resolves most of this. He has been contacted.

--
_This comment has been automatically imported from redmine on 2016-09-28 19:07:16.297845_

**Comment by lukasjuhrich** [comment]
> ### Redmine metadata
> Attribute | Value
> ------------ | --------
> created_on | 2016/09/10 20:17:38 +0200
> user | @lukasjuhrich


---
The „easiest“ way would be using LaTeX as people mentioned.  However, this would dramatically increase the size of the docker container, since some texlive-packages wuld have to be installed.

I thought of the following, more elegant idea: How about creating a separate “latex builder” which exposes a webapi with endpoints @/create/from_template/template_name?param1=foo&username=bar`@caching the created document @/download/9a872938d3ccf2ff<hex, hex!>@ for 24h or something like that.

A corresponding API could be built easily (I imagine) and is a separate software, which makes it easy to delegate to someone.

Any ideas on this @shreyder, @mueslo?

--
_This comment has been automatically imported from redmine on 2016-09-28 19:07:18.930654_

**Comment by lukasjuhrich** [comment]
> ### Redmine metadata
> Attribute | Value
> ------------ | --------
> created_on | 2016/03/05 02:49:51 +0100
> user | @lukasjuhrich


---
I just noted that there is Cairosvg: http://cairosvg.org/documentation/
…which might be an easy way to do this. It just expects some @svg@ data as input, easy as that.

--
_This comment has been automatically imported from redmine on 2016-09-28 19:07:21.741394_

**Comment by lukasjuhrich** [comment]
> ### Redmine metadata
> Attribute | Value
> ------------ | --------
> created_on | 2016/02/02 02:52:59 +0100
> user | @lukasjuhrich


---
This is ultimately important for deployment.

I don't know what's the best practice for creating pdfs in python. After a quick search I stumbled upon Reportlab:

[[http://www.devshed.com/c/a/Python/Python-for-PDF-Generation/#whoCFCPh3TAks368.99]]
[[http://assist-software.net/blog/how-create-pdf-files-python-django-application-using-reportlab]]

On the other hand, would using Latex be possible?  You would have to create a .tex-file on the fly though. Perhaps one could utilize jinja templates?


--
_This comment has been automatically imported from redmine on 2016-09-28 19:07:24.534966_

**Comment by lukasjuhrich** [comment]
@fgrsnau haven't you worked on this? If yes, what's the progress?

@friwi it would be nice if you could summarize the changes you made to the datasheet in the JMultiUserman.

**Comment by fgrsnau** [comment]
Hm. I had a working prototype. The main problem was that it is not easy to persist data between requests. So I build a small database storage backend that maps an integer id to a server object (e.g. the PDF file). But handling invalidation of the entries and other stuff is complicated (partly implemented). (Note that e.g. there might be multiple flask instances, data must be synchronized, hence I used the database as backend. Flask thinks it is not responsible for this kind of stuff.)

PDF generation was done with Cairo. I simply use a PDF as template and render text on top of it. No fancy document generation. There are advantages (easy to use, a pretty(!) user sheets can be designed without knowledge of programming languages) and disadvantages (dependency, no wrapping when text does not fit, etc.).

I will make the code available soon and someone else can decide whether this is the correct approach :)

**Comment by FriwiDev** [comment]
Hier ein Bild vom neuen Formular im JMultiUserman:

![image](https://user-images.githubusercontent.com/12697767/31180393-ce11a61e-a91e-11e7-8bbd-98033ca6cf1a.png)

**Comment by MarauderXtreme** [comment]
I would suggest to leave the IP address out since this is not a necessary information for a member and with the NAT project this probably will be obsolete.

**Comment by lukasjuhrich** [comment]
@MarauderXtreme the NAT project does not obsolete that. Each member will be NATted to an individual, but reserved IP, and IIRC even in a roaming situation (Using WIFI in another building) the user should end up with the same IP.

I do agree however that this is sometimes confusing because people will register this as their static IP, but IMHO the information is still important, because having a static, public IP is one of the very unique features of our network.

**Comment by MarauderXtreme** [comment]
@lukasjuhrich okay. I thought that the outside facing IP with NAT wouldn't be static anymore. Anyway in my opinion the IP address schould not be included in the sheet because this is irrelevant for let's say 80% of our members. For the others we could include a note, that a static IP is assigned. I think those people know how to find out the address.  
To add more to this issue. The rest looks neat so far.

**Comment by lukasjuhrich** [comment]
I agree. Adding a note seems like a neat compromise. 👍

**Comment by lukasjuhrich** [comment]
@fgrsnau What's the state on providing the code? This still is an important blocker.

**Comment by fgrsnau** [comment]
@lukasjuhrich WIP code was available the whole time in branch `printing` (0c2e6cb8978fa1695b6f686877579441f1355312). Obviously, it is incomplete and needs some care. :)

**Comment by lukasjuhrich** [comment]
@fgrsnau my bad. I'm sorry for the unnecessary pressure, should've taken a more careful look.

**Comment by strebbin** [comment]
@lukasjuhrich I reworked it and changed the pdf-generation from cairo, pango and poppler to reportlab. This provides more flexibility in document generation and needs less dependencies.
