### ISSUE TITLE
FixtureDataTestBase doesn't reset fixtures

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#80]
As seen in the broken builds of `lukas:ldap_sync`, the `pycroft.model.user._uid_seq` fixture appears to be not reset.

**Comment by sebschrader** [comment]
Do you have some follow-up on this one?

**Comment by mueslo** [comment]
It was/is due to sequences not being reset between tests.

**Comment by lukasjuhrich** [comment]
Closing, as this is not relevant anymore. If fixture tests are broken, they should be replaced by something using the `factory_boy` base.
