### ISSUE TITLE
Cleanup User Group Management

### ISSUE THREAD

**Issue by lightning1** [agdsn/pycroft#85]
The following groups are not accurate anymore:
- Org → Aktiv
- Umzug aus anderer Sektion → not necessary anymore
- Semesterbeitrag in anderer Sektion entrichtet → not necessary anymore

**Comment by lukasjuhrich** [comment]
Please note that pycroft only „knoows“ the special groups mentioned in the config plus the hard-coded property strings, so the tasklist would be to remove:

- `Config.moved_from_division_group_id`
- `Config.already_paid_semester_fee_group_id`

Plus lots of other things that can be removed from the config, but that's unrelated.

**Comment by toothstone** [comment]
The Org cleanup will be handled in #195, I should probably take care of the other two legacy groups since I implemented them :D

**Comment by ibot3** [comment]
@toothstone 
I already removed them in bed1c65b27cfa290cbd7f1e2803189e454207939
