### ISSUE TITLE
Add schema version control

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#93]
Using a tool like [alembic](http://alembic.zzzcomputing.com/en/latest/tutorial.html), the schema has to be under version control at the time of the first deployment.

In the course of the above, we should provide an easy way of bootstrapping the pycroft database (ideally in the entrypoint of the docker container) so that the user does not have to run manual commands to have a working pycroft instance up-and-running.

**Comment by lukasjuhrich** [comment]
See the valuable information in [this article] (https://www.compose.com/articles/schema-migrations-with-alembic-python-and-postgresql/).

**Comment by lukasjuhrich** [comment]
I drafted a setup with `alembic`:

https://github.com/agdsn/pycroft/compare/develop...lukasjuhrich:alembic?expand=1

**Comment by lukasjuhrich** [comment]
I'm currently struggling with how to implement automatic version verification in `server_run`.
Unfortunately, `alembic` doesn't provide an API for running their commands in python (the one that does is unusable, because results are printed instead of returned).

In the worst case, we can just issue all the commands manually, it's not too hard to run `alembic stamp head` after the importer. However, this would require modifying the URI in the checked-in file `alembic.ini`.

**Comment by sebschrader** [comment]
Have you found [this](https://stackoverflow.com/a/24431451/2350268) discussion on StackOverflow?

**Comment by lukasjuhrich** [comment]
No, but I was aware that the internals use a `MigrationContext`. I didn't want to touch that though, because it seemed too much like fishing in the internals for me. Howver, because this seems like the only sensible option, I will look into it.
