### ISSUE TITLE
Create Traffic Group: Broken interval field

### ISSUE THREAD

**Issue by toothstone** [agdsn/pycroft#94]
Traffic groups require an interval, but the input field allows only dates, and so the form validation fails on submission.

Steps to reproduce:
1. Go to /properties/traffic_group/create
2. Fill name, amount and cap.
3. Try to enter a meaningful interval ⇒ converted to current date, date picker shown
4. Submit

**Comment by lukasjuhrich** [comment]
I just realized my fix kind of broke it, because the field values now default to an empty string instead of `0 mons … 0 secs`.
